version: "3.4"

services:
  postgresql_database:
    container_name: postgresql_database
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - databasedata:/var/lib/postgresql/data/

  department-automation-backend:
    image: vladsokol/department-automation-backend:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DATABASE_URL: "${CONNECTION_STRING}"
    depends_on:
      - postgresql_database

  department-automation-client:
    image: vladsokol/department-automation-client:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  databasedata:
